// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://neuaqvqwwmthwyqbbces.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ldWFxdnF3d210aHd5cWJiY2VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNTI2NTEsImV4cCI6MjA3NDcyODY1MX0.zhV-KPSj5QQBcYHEu9OJ9ObZLt_8AIW8LII9WAi1f20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);